import { NextRequest, NextResponse } from 'next/server';
import { JobberOAuth } from '@/lib/jobber-oauth';

// This endpoint can be called by a cron job to monitor and auto-refresh tokens
// You can set up Vercel Cron Jobs or use an external service to call this daily
export async function POST(request: NextRequest) {
  try {
    const oauth = new JobberOAuth();
    const tokenInfo = oauth.getTokenInfo();

    if (!tokenInfo) {
      console.error('❌ No valid Jobber token found');
      return NextResponse.json(
        { error: 'No valid token found' },
        { status: 400 }
      );
    }

    const daysUntilExpiry = Math.ceil(
      (tokenInfo.expiresAt.getTime() - Date.now()) / (1000 * 60 * 60 * 24)
    );

    // If token expires in 7 days or less, try to refresh
    if (daysUntilExpiry <= 7) {
      console.log(`⚠️ Token expires in ${daysUntilExpiry} days, refreshing...`);

      try {
        const newTokens = await oauth.refreshAccessToken();

        // Send email notification with new tokens
        await sendTokenUpdateNotification(newTokens, daysUntilExpiry);

        return NextResponse.json({
          success: true,
          action: 'refreshed',
          message: `Token refreshed (was expiring in ${daysUntilExpiry} days)`,
          daysUntilExpiry,
          emailSent: true,
        });
      } catch (refreshError) {
        // If refresh fails, send urgent notification
        await sendUrgentTokenNotification(tokenInfo.expiresAt);

        return NextResponse.json({
          success: false,
          action: 'refresh_failed',
          error:
            refreshError instanceof Error
              ? refreshError.message
              : 'Unknown error',
          daysUntilExpiry,
          emailSent: true,
        });
      }
    }

    // Token is still valid for more than 7 days
    return NextResponse.json({
      success: true,
      action: 'no_action_needed',
      message: `Token is valid for ${daysUntilExpiry} more days`,
      expiresAt: tokenInfo.expiresAt,
      daysUntilExpiry,
    });
  } catch (error) {
    console.error('Token monitoring error:', error);
    return NextResponse.json(
      { error: 'Token monitoring failed' },
      { status: 500 }
    );
  }
}

// Send email notification with new tokens
async function sendTokenUpdateNotification(
  newTokens: any,
  daysUntilExpiry: number
) {
  try {
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <title>Jobber Tokens Refreshed - Hometown Handyman</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #2563eb; color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }
    .content { background: #f9f9f9; padding: 20px; border: 1px solid #ddd; }
    .token-box { background: #f0f8ff; border: 1px solid #2563eb; padding: 15px; border-radius: 4px; margin: 10px 0; font-family: monospace; word-break: break-all; }
    .urgent { background: #fee; border-color: #f00; }
    .footer { background: #f1f1f1; padding: 15px; border-radius: 0 0 8px 8px; text-align: center; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🔄 Jobber Tokens Refreshed</h1>
    <p>Automatic token refresh completed</p>
  </div>
  
  <div class="content">
    <p>Your Jobber API tokens were automatically refreshed because they were expiring in ${daysUntilExpiry} days.</p>
    
    <h3>⚠️ Action Required</h3>
    <p>Update these environment variables in Vercel within 24 hours:</p>
    
    <div class="token-box">
      <strong>JOBBER_ACCESS_TOKEN=</strong><br>
      ${newTokens.access_token}
    </div>
    
    <div class="token-box">
      <strong>JOBBER_REFRESH_TOKEN=</strong><br>
      ${newTokens.refresh_token}
    </div>
    
    <h3>Steps to Update:</h3>
    <ol>
      <li>Go to <a href="https://vercel.com/dashboard">Vercel Dashboard</a></li>
      <li>Select your Hometown Handyman project</li>
      <li>Go to Settings → Environment Variables</li>
      <li>Update JOBBER_ACCESS_TOKEN and JOBBER_REFRESH_TOKEN</li>
      <li>Redeploy the application</li>
    </ol>
    
    <p><strong>Important:</strong> The system will continue working temporarily, but you must update these tokens in Vercel for permanent use.</p>
  </div>
  
  <div class="footer">
    <p>Hometown Handyman - Automated Token Management</p>
    <p>This email was automatically generated by your website's token monitoring system.</p>
  </div>
</body>
</html>
    `;

    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.EMAIL_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: process.env.FROM_EMAIL,
        to: [process.env.ESTIMATES_EMAIL],
        subject: '🔄 Jobber Tokens Refreshed - Action Required',
        html: htmlContent,
        reply_to: process.env.REPLY_TO_EMAIL,
      }),
    });

    if (!response.ok) {
      throw new Error(`Email send failed: ${response.statusText}`);
    }

    console.log('✅ Token update notification sent successfully');
  } catch (error) {
    console.error('❌ Failed to send token update notification:', error);
  }
}

// Send urgent notification when refresh fails
async function sendUrgentTokenNotification(expiresAt: Date) {
  try {
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <title>URGENT: Jobber Token Refresh Failed - Hometown Handyman</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #dc2626; color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }
    .content { background: #fee; padding: 20px; border: 1px solid #dc2626; }
    .footer { background: #f1f1f1; padding: 15px; border-radius: 0 0 8px 8px; text-align: center; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 URGENT: Token Refresh Failed</h1>
    <p>Manual intervention required</p>
  </div>
  
  <div class="content">
    <p><strong>Your Jobber API tokens expire on: ${expiresAt.toLocaleString()}</strong></p>
    
    <p>Automatic token refresh failed. Your website's Jobber integration will stop working when the tokens expire.</p>
    
    <h3>Immediate Action Required:</h3>
    <ol>
      <li>Contact Jobber support to resolve token refresh issues</li>
      <li>Or manually generate new tokens from Jobber developer portal</li>
      <li>Update tokens in Vercel environment variables</li>
    </ol>
    
    <p><strong>Backup:</strong> Your email fallback system will continue capturing leads even if Jobber integration fails.</p>
  </div>
  
  <div class="footer">
    <p>Hometown Handyman - Critical Alert</p>
  </div>
</body>
</html>
    `;

    await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.EMAIL_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: process.env.FROM_EMAIL,
        to: [process.env.ESTIMATES_EMAIL],
        subject: '🚨 URGENT: Jobber Token Refresh Failed',
        html: htmlContent,
        reply_to: process.env.REPLY_TO_EMAIL,
      }),
    });

    console.log('🚨 Urgent token notification sent');
  } catch (error) {
    console.error('❌ Failed to send urgent notification:', error);
  }
}
